// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using karnel_travels_mvc.Data;

#nullable disable

namespace karnel_travels_mvc.Migrations
{
    [DbContext(typeof(KarnelTravelContext))]
    [Migration("20251223173445_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("karnel_travels_mvc.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 25,
                            Description = "Luxury 5-star hotel with sea view rooms, rooftop restaurant, and spa facilities.",
                            Location = "Mumbai",
                            Name = "Grand Plaza Hotel",
                            Price = 5500m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 18,
                            Description = "Premium hotel near India Gate with conference halls and fine dining.",
                            Location = "Delhi",
                            Name = "Taj Palace",
                            Price = 6200m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 32,
                            Description = "Comfortable beachfront hotel with modern amenities and seafood restaurant.",
                            Location = "Chennai",
                            Name = "Beach View Inn",
                            Price = 3200m,
                            Quality = "4-Star"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 15,
                            Description = "Converted palace hotel with traditional Rajasthani decor and cultural performances.",
                            Location = "Jaipur",
                            Name = "Heritage Hotel",
                            Price = 4800m,
                            Quality = "4-Star"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 28,
                            Description = "Resort-style hotel with pool, beach access, and water sports facilities.",
                            Location = "Goa",
                            Name = "Coastal Retreat",
                            Price = 4200m,
                            Quality = "4-Star"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 42,
                            Description = "Budget-friendly hotel in city center with basic amenities and free WiFi.",
                            Location = "Bangalore",
                            Name = "City Center Lodge",
                            Price = 1800m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 20,
                            Description = "Hill station hotel with panoramic mountain views and cozy fireplace rooms.",
                            Location = "Shimla",
                            Name = "Mountain View Hotel",
                            Price = 3500m,
                            Quality = "3-Star"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Resort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 15,
                            Capacity = 120,
                            Description = "Luxury beachfront resort with private villas, infinity pool, spa, and water sports.",
                            Location = "Goa",
                            Name = "Ocean Paradise Resort",
                            Price = 8500m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 22,
                            Capacity = 80,
                            Description = "Eco-resort on backwaters with houseboat stays, Ayurvedic spa, and yoga sessions.",
                            Location = "Alleppey",
                            Name = "Backwater Bliss Resort",
                            Price = 6500m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 18,
                            Capacity = 60,
                            Description = "Mountain resort with cottages, bonfire evenings, trekking, and tea plantation tours.",
                            Location = "Ooty",
                            Name = "Hill Station Retreat",
                            Price = 5200m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 25,
                            Capacity = 100,
                            Description = "Desert camp experience with camel safari, cultural programs, and traditional Rajasthani hospitality.",
                            Location = "Jaisalmer",
                            Name = "Desert Safari Resort",
                            Price = 4800m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 12,
                            Capacity = 50,
                            Description = "Nature resort near national park with jungle safaris, bird watching, and campfires.",
                            Location = "Jim Corbett",
                            Name = "Wildlife Adventure Resort",
                            Price = 7200m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 8,
                            Capacity = 40,
                            Description = "Tropical island resort with scuba diving, snorkeling, beach activities, and coral reef tours.",
                            Location = "Andaman",
                            Name = "Island Paradise Resort",
                            Price = 9500m,
                            Quality = "Luxury"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 50,
                            Description = "Authentic Indian cuisine with North and South Indian specialties, tandoor dishes.",
                            Location = "Mumbai",
                            Name = "Spice Garden",
                            Price = 800m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 40,
                            Description = "Fresh seafood restaurant specializing in coastal delicacies and traditional recipes.",
                            Location = "Chennai",
                            Name = "Coastal Kitchen",
                            Price = 650m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 35,
                            Description = "Rajasthani royal cuisine in heritage ambiance with live folk music.",
                            Location = "Jaipur",
                            Name = "Royal Dine",
                            Price = 950m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 60,
                            Description = "Beachside restaurant serving Goan fish curry, vindaloo, and Portuguese pastries.",
                            Location = "Goa",
                            Name = "Goan Shack",
                            Price = 550m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 100,
                            Description = "Popular street food court offering chaat, momos, kebabs, and regional snacks.",
                            Location = "Delhi",
                            Name = "Street Food Hub",
                            Price = 250m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 45,
                            Description = "Traditional Kerala cuisine with appam, stew, fish moilee, and sadya meals.",
                            Location = "Kochi",
                            Name = "Kerala Kitchen",
                            Price = 450m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 38,
                            Description = "Modern fusion restaurant blending Indian and continental flavors.",
                            Location = "Bangalore",
                            Name = "Fusion Bistro",
                            Price = 750m,
                            Quality = "Premium"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TouristSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TouristSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "One of the longest urban beaches in the world, perfect for evening walks and local street food.",
                            IsAvailable = true,
                            Location = "Chennai",
                            Name = "Marina Beach",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Iconic white marble mausoleum, one of the Seven Wonders of the World.",
                            IsAvailable = true,
                            Location = "Agra",
                            Name = "Taj Mahal",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Historic arch monument overlooking the Arabian Sea, built during British rule.",
                            IsAvailable = true,
                            Location = "Mumbai",
                            Name = "Gateway of India",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Palace of Winds, five-story structure with unique honeycomb design and 953 small windows.",
                            IsAvailable = true,
                            Location = "Jaipur",
                            Name = "Hawa Mahal",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Historic Hindu temple dedicated to Meenakshi, featuring stunning Dravidian architecture.",
                            IsAvailable = true,
                            Location = "Madurai",
                            Name = "Meenakshi Temple",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Beautiful tropical beaches with water sports, nightlife, and Portuguese heritage.",
                            IsAvailable = true,
                            Location = "Goa",
                            Name = "Goa Beaches",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Network of lagoons and lakes with houseboat cruises through scenic waterways.",
                            IsAvailable = true,
                            Location = "Alleppey",
                            Name = "Kerala Backwaters",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Massive red sandstone fort complex built by Mughal emperor Shah Jahan.",
                            IsAvailable = false,
                            Location = "Delhi",
                            Name = "Red Fort",
                            Quality = "Good"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TravelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TravelInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Description = "Scenic train journey through Western Ghats. Daily service, AC and sleeper coaches available. Duration: 12 hours.",
                            Price = 850m,
                            Route = "Mumbai to Goa (Konkan Railway)",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Description = "Multiple daily flights by major carriers. Flight duration: 2.5 hours. Economy and business class available.",
                            Price = 4500m,
                            Route = "Delhi to Mumbai",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Description = "Luxury Volvo AC buses running every hour. Comfortable seating, onboard entertainment. Duration: 3.5 hours.",
                            Price = 450m,
                            Route = "Bangalore to Mysore",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            Description = "Premium express train with meals included. Comfortable AC chairs. Duration: 4.5 hours.",
                            Price = 750m,
                            Route = "Delhi to Jaipur (Shatabdi Express)",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Description = "Ferry service from Gateway of India. Scenic boat ride. Duration: 1 hour one way.",
                            Price = 200m,
                            Route = "Mumbai to Elephanta Caves",
                            TransportType = "Ferry"
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Description = "Regular bus service along East Coast Road. Semi-sleeper and seater options. Duration: 3 hours.",
                            Price = 350m,
                            Route = "Chennai to Pondicherry",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Description = "Daily flights connecting South and East India. Duration: 2 hours. Multiple time slots.",
                            Price = 5200m,
                            Route = "Chennai to Kolkata",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 8,
                            Availability = false,
                            Description = "Kerala coastal train with beautiful Arabian Sea views. Duration: 4 hours.",
                            Price = 280m,
                            Route = "Kochi to Trivandrum",
                            TransportType = "Train"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
