// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using karnel_travels_mvc.Data;

#nullable disable

namespace karnel_travels_mvc.Migrations
{
    [DbContext(typeof(KarnelTravelContext))]
    [Migration("20260109144714_location-changes")]
    partial class locationchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("karnel_travels_mvc.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 20,
                            Description = "Luxury hotel near Mall Road with fine dining and conference halls.",
                            Location = "Lahore",
                            Name = "Pearl Continental Hotel",
                            Price = 22000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 15,
                            Description = "Premium hotel offering traditional architecture and luxury services.",
                            Location = "Islamabad",
                            Name = "Serena Hotel",
                            Price = 26000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 25,
                            Description = "Business-class hotel in city center with rooftop dining.",
                            Location = "Karachi",
                            Name = "Avari Towers",
                            Price = 18000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 30,
                            Description = "Comfortable mid-range hotel with modern amenities.",
                            Location = "Faisalabad",
                            Name = "Hotel One",
                            Price = 9000m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 18,
                            Description = "Mountain-view hotel popular with tourists and trekkers.",
                            Location = "Hunza",
                            Name = "Hunza View Hotel",
                            Price = 7500m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 35,
                            Description = "Affordable stay with basic facilities for travelers.",
                            Location = "Quetta",
                            Name = "Shelton Guest House",
                            Price = 5500m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 12,
                            Description = "Famous resort hotel near Lower Kachura Lake.",
                            Location = "Skardu",
                            Name = "Shangrila Resort Hotel",
                            Price = 16000m,
                            Quality = "4-Star"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Resort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 10,
                            Capacity = 90,
                            Description = "Famous red-roof resort near Lower Kachura Lake.",
                            Location = "Skardu",
                            Name = "Shangrila Resort",
                            Price = 20000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 6,
                            Capacity = 40,
                            Description = "Restored heritage palace offering luxury stays.",
                            Location = "Khaplu",
                            Name = "Serena Khaplu Palace",
                            Price = 24000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 14,
                            Capacity = 70,
                            Description = "Scenic riverside resort popular among families.",
                            Location = "Naran",
                            Name = "Arcadian Riverside",
                            Price = 14000m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 20,
                            Capacity = 85,
                            Description = "Nature resort surrounded by mountains and rivers.",
                            Location = "Swat",
                            Name = "Green Retreat",
                            Price = 11000m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 16,
                            Capacity = 60,
                            Description = "Peaceful resort near Quaid-e-Azam Residency.",
                            Location = "Ziarat",
                            Name = "Ziarat Residency Resort",
                            Price = 9000m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 8,
                            Capacity = 50,
                            Description = "Coastal resort offering sea views and private cottages.",
                            Location = "Gwadar",
                            Name = "Beach Luxury Resort",
                            Price = 17000m,
                            Quality = "Luxury"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 60,
                            Description = "Famous hilltop restaurant offering Pakistani and continental cuisine.",
                            Location = "Islamabad",
                            Name = "Monal",
                            Price = 1800m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 45,
                            Description = "Traditional Pakistani food with Badshahi Mosque view.",
                            Location = "Lahore",
                            Name = "Haveli Restaurant",
                            Price = 1500m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 70,
                            Description = "Popular seaside restaurant known for BBQ and seafood.",
                            Location = "Karachi",
                            Name = "Kolachi",
                            Price = 1700m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 100,
                            Description = "Iconic biryani spot famous nationwide.",
                            Location = "Karachi",
                            Name = "Student Biryani",
                            Price = 450m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 40,
                            Description = "Casual dining with desi and Chinese menu.",
                            Location = "Islamabad",
                            Name = "Cafe Islamabad",
                            Price = 900m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 55,
                            Description = "Well-known for traditional desi breakfast and karahi.",
                            Location = "Lahore",
                            Name = "Usmania Restaurant",
                            Price = 600m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 30,
                            Description = "Local cafe serving organic Hunza food and desserts.",
                            Location = "Hunza",
                            Name = "Cafe De Hunza",
                            Price = 800m,
                            Quality = "Standard"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TouristSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TouristSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Famous for snow-capped mountains, Attabad Lake, and breathtaking landscapes.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Hunza Valley",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 2,
                            Description = "One of the largest historic mosques in the world, built during the Mughal era.",
                            IsAvailable = true,
                            Location = "Lahore",
                            Name = "Badshahi Mosque",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Iconic modern mosque at the foothills of Margalla Hills.",
                            IsAvailable = true,
                            Location = "Islamabad",
                            Name = "Faisal Mosque",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Popular hill station known for cool climate, chairlifts, and scenic views.",
                            IsAvailable = true,
                            Location = "Murree",
                            Name = "Murree Hills",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Historic palace showcasing art exhibitions and Sindh heritage.",
                            IsAvailable = true,
                            Location = "Karachi",
                            Name = "Mohatta Palace",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gateway to K2 and famous for lakes, forts, and trekking routes.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Skardu",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Massive square fort in Cholistan Desert with rich Nawabi history.",
                            IsAvailable = true,
                            Location = "Bahawalpur",
                            Name = "Derawar Fort",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 8,
                            Description = "UNESCO World Heritage site with one of the largest graveyards in the world.",
                            IsAvailable = false,
                            Location = "Thatta",
                            Name = "Makli Necropolis",
                            Quality = "Good"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TravelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TravelInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Description = "Daily flights by PIA and private airlines. Duration: 2 hours.",
                            Price = 22000m,
                            Route = "Karachi to Islamabad",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Description = "Modern express train with AC coaches. Duration: 18 hours.",
                            Price = 6500m,
                            Route = "Lahore to Karachi (Green Line)",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Description = "Luxury coach service with frequent departures.",
                            Price = 600m,
                            Route = "Islamabad to Murree",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            Description = "Comfortable Daewoo bus service. Duration: 3 hours.",
                            Price = 1200m,
                            Route = "Lahore to Faisalabad",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Description = "Weather-dependent scenic flight over mountains.",
                            Price = 26000m,
                            Route = "Islamabad to Skardu",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Description = "Hourly bus service via Super Highway.",
                            Price = 900m,
                            Route = "Karachi to Hyderabad",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Description = "Intercity rail service. Duration: 4 hours.",
                            Price = 1500m,
                            Route = "Rawalpindi to Peshawar",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 8,
                            Availability = false,
                            Description = "4x4 jeep service for high-altitude national park.",
                            Price = 8000m,
                            Route = "Skardu to Deosai Plains",
                            TransportType = "Jeep"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
