// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using karnel_travels_mvc.Data;

#nullable disable

namespace karnel_travels_mvc.Migrations
{
    [DbContext(typeof(KarnelTravelContext))]
    [Migration("20260109150838_added-more-location")]
    partial class addedmorelocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("karnel_travels_mvc.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 20,
                            Description = "Luxury hotel near Mall Road with fine dining and conference halls.",
                            Location = "Lahore",
                            Name = "Pearl Continental Hotel",
                            Price = 22000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 15,
                            Description = "Premium hotel offering traditional architecture and luxury services.",
                            Location = "Islamabad",
                            Name = "Serena Hotel",
                            Price = 26000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 25,
                            Description = "Business-class hotel in city center with rooftop dining.",
                            Location = "Karachi",
                            Name = "Avari Towers",
                            Price = 18000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 30,
                            Description = "Comfortable mid-range hotel with modern amenities.",
                            Location = "Faisalabad",
                            Name = "Hotel One",
                            Price = 9000m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 18,
                            Description = "Mountain-view hotel popular with tourists and trekkers.",
                            Location = "Hunza",
                            Name = "Hunza View Hotel",
                            Price = 7500m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 35,
                            Description = "Affordable stay with basic facilities for travelers.",
                            Location = "Quetta",
                            Name = "Shelton Guest House",
                            Price = 5500m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 12,
                            Description = "Famous resort hotel near Lower Kachura Lake.",
                            Location = "Skardu",
                            Name = "Shangrila Resort Hotel",
                            Price = 16000m,
                            Quality = "4-Star"
                        },
                        new
                        {
                            Id = 8,
                            Availability = 20,
                            Description = "Luxury hotel in Islamabad with modern amenities.",
                            Location = "Islamabad",
                            Name = "Islamabad Marriott Hotel",
                            Price = 23000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 9,
                            Availability = 18,
                            Description = "Luxury hotel on Mall Road with historic charm.",
                            Location = "Lahore",
                            Name = "Avari Towers Lahore",
                            Price = 20000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 10,
                            Availability = 15,
                            Description = "5-star hotel serving Islamabad/Rawalpindi area.",
                            Location = "Rawalpindi",
                            Name = "Pearl Continental Rawalpindi",
                            Price = 22000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 11,
                            Availability = 18,
                            Description = "Downtown luxury hotel with international brand.",
                            Location = "Karachi",
                            Name = "Karachi Marriott Hotel",
                            Price = 25000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 12,
                            Availability = 22,
                            Description = "Modern hotel in Clifton area with upscale dining.",
                            Location = "Karachi",
                            Name = "Hilton Karachi",
                            Price = 18000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 13,
                            Availability = 25,
                            Description = "Boutique hotel in Karimabad with mountain views.",
                            Location = "Hunza",
                            Name = "Serena Inn Hunza",
                            Price = 12000m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 14,
                            Availability = 20,
                            Description = "Popular hotel near Duikar with panoramic Hunza valley views.",
                            Location = "Hunza",
                            Name = "Eagle’s Nest Hotel",
                            Price = 15000m,
                            Quality = "4-Star"
                        },
                        new
                        {
                            Id = 15,
                            Availability = 12,
                            Description = "Heritage hotel in a restored fort near Skardu.",
                            Location = "Skardu",
                            Name = "Serena Shigar Fort",
                            Price = 22000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 16,
                            Availability = 10,
                            Description = "5-star hill resort near Madyan with ski facilities.",
                            Location = "Swat",
                            Name = "Pearl Continental Swat (Madyan)",
                            Price = 20000m,
                            Quality = "5-Star"
                        },
                        new
                        {
                            Id = 17,
                            Availability = 30,
                            Description = "Mid-range hotel in Swat Valley with modern amenities.",
                            Location = "Swat",
                            Name = "Swat Continental Hotel",
                            Price = 8000m,
                            Quality = "3-Star"
                        },
                        new
                        {
                            Id = 18,
                            Availability = 14,
                            Description = "Luxury mountain resort at Malam Jabba ski area.",
                            Location = "Swat",
                            Name = "Serena Hotel Malam Jabba",
                            Price = 15000m,
                            Quality = "5-Star"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Resort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Resorts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 10,
                            Capacity = 90,
                            Description = "Famous red-roof resort near Lower Kachura Lake.",
                            Location = "Skardu",
                            Name = "Shangrila Resort",
                            Price = 20000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 6,
                            Capacity = 40,
                            Description = "Restored heritage palace offering luxury stays.",
                            Location = "Khaplu",
                            Name = "Serena Khaplu Palace",
                            Price = 24000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 14,
                            Capacity = 70,
                            Description = "Scenic riverside resort popular among families.",
                            Location = "Naran",
                            Name = "Arcadian Riverside",
                            Price = 14000m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 20,
                            Capacity = 85,
                            Description = "Nature resort surrounded by mountains and rivers.",
                            Location = "Swat",
                            Name = "Green Retreat",
                            Price = 11000m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 16,
                            Capacity = 60,
                            Description = "Peaceful resort near Quaid-e-Azam Residency.",
                            Location = "Ziarat",
                            Name = "Ziarat Residency Resort",
                            Price = 9000m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 8,
                            Capacity = 50,
                            Description = "Coastal resort offering sea views and private cottages.",
                            Location = "Gwadar",
                            Name = "Beach Luxury Resort",
                            Price = 17000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 8,
                            Capacity = 70,
                            Description = "Luxury mountain resort with ski facilities in Swat.",
                            Location = "Malam Jabba",
                            Name = "Swat Serena Resort",
                            Price = 25000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 8,
                            Availability = 10,
                            Capacity = 60,
                            Description = "High-end hill resort overlooking the Kunhar River.",
                            Location = "Naran",
                            Name = "Pearl Continental Resort Naran",
                            Price = 22000m,
                            Quality = "Luxury"
                        },
                        new
                        {
                            Id = 9,
                            Availability = 20,
                            Capacity = 50,
                            Description = "Remote resort at the base of Nanga Parbat (Fairy Meadows).",
                            Location = "Nanga Parbat Basecamp",
                            Name = "Fairy Meadows Resort",
                            Price = 8000m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 10,
                            Availability = 15,
                            Capacity = 40,
                            Description = "Eco-resort surrounded by forests near Gilgit.",
                            Location = "Naltar",
                            Name = "Jungle Resort Naltar",
                            Price = 9000m,
                            Quality = "Standard"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = 60,
                            Description = "Famous hilltop restaurant offering Pakistani and continental cuisine.",
                            Location = "Islamabad",
                            Name = "Monal",
                            Price = 1800m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 2,
                            Availability = 45,
                            Description = "Traditional Pakistani food with Badshahi Mosque view.",
                            Location = "Lahore",
                            Name = "Haveli Restaurant",
                            Price = 1500m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 3,
                            Availability = 70,
                            Description = "Popular seaside restaurant known for BBQ and seafood.",
                            Location = "Karachi",
                            Name = "Kolachi",
                            Price = 1700m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 4,
                            Availability = 100,
                            Description = "Iconic biryani spot famous nationwide.",
                            Location = "Karachi",
                            Name = "Student Biryani",
                            Price = 450m,
                            Quality = "Budget"
                        },
                        new
                        {
                            Id = 5,
                            Availability = 40,
                            Description = "Casual dining with desi and Chinese menu.",
                            Location = "Islamabad",
                            Name = "Cafe Islamabad",
                            Price = 900m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 6,
                            Availability = 55,
                            Description = "Well-known for traditional desi breakfast and karahi.",
                            Location = "Lahore",
                            Name = "Usmania Restaurant",
                            Price = 600m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 7,
                            Availability = 30,
                            Description = "Local cafe serving organic Hunza food and desserts.",
                            Location = "Hunza",
                            Name = "Cafe De Hunza",
                            Price = 800m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 8,
                            Availability = 50,
                            Description = "Famous for spicy karahi dishes in Lahore.",
                            Location = "Lahore",
                            Name = "Butt Karahi",
                            Price = 600m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 9,
                            Availability = 30,
                            Description = "Popular restaurant with Lahore Fort views.",
                            Location = "Lahore",
                            Name = "Cooco's Den",
                            Price = 1200m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 10,
                            Availability = 25,
                            Description = "Outdoor Italian restaurant in F-6 area.",
                            Location = "Islamabad",
                            Name = "Tuscany Courtyard",
                            Price = 2000m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 11,
                            Availability = 35,
                            Description = "Coffee shop and bakery known for desserts.",
                            Location = "Islamabad",
                            Name = "Burning Brownie",
                            Price = 800m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 12,
                            Availability = 40,
                            Description = "Upscale Mediterranean restaurant in Clifton.",
                            Location = "Karachi",
                            Name = "Okra",
                            Price = 2500m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 13,
                            Availability = 60,
                            Description = "Well-known BBQ and grill restaurant in Clifton.",
                            Location = "Karachi",
                            Name = "BBQ Tonight",
                            Price = 1700m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 14,
                            Availability = 30,
                            Description = "Contemporary cafe and restaurant in Clifton.",
                            Location = "Karachi",
                            Name = "Xander's",
                            Price = 1800m,
                            Quality = "Premium"
                        },
                        new
                        {
                            Id = 15,
                            Availability = 20,
                            Description = "Popular cafe in Karimabad serving local Hunza dishes.",
                            Location = "Hunza",
                            Name = "Amber Cafe",
                            Price = 800m,
                            Quality = "Standard"
                        },
                        new
                        {
                            Id = 16,
                            Availability = 15,
                            Description = "Alpine-style restaurant at Malam Jabba resort.",
                            Location = "Swat",
                            Name = "Peach Hotel Restaurant",
                            Price = 1000m,
                            Quality = "Standard"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TouristSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TouristSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Famous for snow-capped mountains, Attabad Lake, and breathtaking landscapes.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Hunza Valley",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 2,
                            Description = "One of the largest historic mosques in the world, built during the Mughal era.",
                            IsAvailable = true,
                            Location = "Lahore",
                            Name = "Badshahi Mosque",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Iconic modern mosque at the foothills of Margalla Hills.",
                            IsAvailable = true,
                            Location = "Islamabad",
                            Name = "Faisal Mosque",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Popular hill station known for cool climate, chairlifts, and scenic views.",
                            IsAvailable = true,
                            Location = "Murree",
                            Name = "Murree Hills",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Historic palace showcasing art exhibitions and Sindh heritage.",
                            IsAvailable = true,
                            Location = "Karachi",
                            Name = "Mohatta Palace",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Gateway to K2 and famous for lakes, forts, and trekking routes.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Skardu",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Massive square fort in Cholistan Desert with rich Nawabi history.",
                            IsAvailable = true,
                            Location = "Bahawalpur",
                            Name = "Derawar Fort",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 8,
                            Description = "UNESCO World Heritage site with one of the largest graveyards in the world.",
                            IsAvailable = false,
                            Location = "Thatta",
                            Name = "Makli Necropolis",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Historic Mughal fort adjacent to Badshahi Mosque.",
                            IsAvailable = true,
                            Location = "Lahore",
                            Name = "Lahore Fort",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 10,
                            Description = "National monument where Pakistan Resolution was passed.",
                            IsAvailable = true,
                            Location = "Lahore",
                            Name = "Minar-e-Pakistan",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 11,
                            Description = "17th century Mughal mosque famous for its frescoes.",
                            IsAvailable = true,
                            Location = "Lahore",
                            Name = "Wazir Khan Mosque",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Popular city beach on the Arabian Sea, known for camel rides and food stalls.",
                            IsAvailable = true,
                            Location = "Karachi",
                            Name = "Clifton Beach",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Mausoleum of Quaid-e-Azam Muhammad Ali Jinnah, an iconic Karachi landmark.",
                            IsAvailable = true,
                            Location = "Karachi",
                            Name = "Mazar-e-Quaid",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 14,
                            Description = "National monument symbolizing Pakistan’s unity (foothills of Margalla).",
                            IsAvailable = true,
                            Location = "Islamabad",
                            Name = "Pakistan Monument",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Hilltop park with panoramic views of Islamabad city.",
                            IsAvailable = true,
                            Location = "Islamabad",
                            Name = "Daman-e-Koh",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cultural museum showcasing Pakistan’s diverse traditions.",
                            IsAvailable = true,
                            Location = "Islamabad",
                            Name = "Lok Virsa Heritage Museum",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 17,
                            Description = "8th-century fort overlooking Karimabad in Hunza Valley.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Baltit Fort",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Distinctive jagged peaks along the Karakoram Highway in Hunza.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Passu Cones",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Scenic turquoise lake in Hunza (formed by 2010 landslide).",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Attabad Lake",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 20,
                            Description = "High-altitude plateau (Land of Giants) near Skardu, famed for wildflowers.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Deosai National Park",
                            Quality = "Excellent"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Mountain lake near Skardu supplying fresh water to the valley.",
                            IsAvailable = true,
                            Location = "Gilgit-Baltistan",
                            Name = "Satpara Lake",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Mountain resort and ski area in Swat Valley.",
                            IsAvailable = true,
                            Location = "Swat",
                            Name = "Malam Jabba",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Alpine lake in the Ushu Valley of Swat (fishing & boating).",
                            IsAvailable = true,
                            Location = "Swat",
                            Name = "Mahodand Lake",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Cedar forest in Swat, gateway to Mahodand Lake.",
                            IsAvailable = true,
                            Location = "Swat",
                            Name = "Ushu Forest",
                            Quality = "Good"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Archaeological museum in Saidu Sharif, showcasing Gandharan artifacts.",
                            IsAvailable = true,
                            Location = "Swat",
                            Name = "Swat Museum",
                            Quality = "Standard"
                        });
                });

            modelBuilder.Entity("karnel_travels_mvc.Models.TravelInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TravelInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            Description = "Daily flights by PIA and private airlines. Duration: 2 hours.",
                            Price = 22000m,
                            Route = "Karachi to Islamabad",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            Description = "Modern express train with AC coaches. Duration: 18 hours.",
                            Price = 6500m,
                            Route = "Lahore to Karachi (Green Line)",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            Description = "Luxury coach service with frequent departures.",
                            Price = 600m,
                            Route = "Islamabad to Murree",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            Description = "Comfortable Daewoo bus service. Duration: 3 hours.",
                            Price = 1200m,
                            Route = "Lahore to Faisalabad",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            Description = "Weather-dependent scenic flight over mountains.",
                            Price = 26000m,
                            Route = "Islamabad to Skardu",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            Description = "Hourly bus service via Super Highway.",
                            Price = 900m,
                            Route = "Karachi to Hyderabad",
                            TransportType = "Bus"
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            Description = "Intercity rail service. Duration: 4 hours.",
                            Price = 1500m,
                            Route = "Rawalpindi to Peshawar",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 8,
                            Availability = false,
                            Description = "4x4 jeep service for high-altitude national park.",
                            Price = 8000m,
                            Route = "Skardu to Deosai Plains",
                            TransportType = "Jeep"
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            Description = "Daily flights (PIA/SereneAir). Duration ~1h45.",
                            Price = 10000m,
                            Route = "Karachi to Lahore",
                            TransportType = "Flight"
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            Description = "Express train (Awam/Jaffar Express). Duration ~6h.",
                            Price = 1800m,
                            Route = "Lahore to Peshawar",
                            TransportType = "Train"
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            Description = "Daewoo Express bus service. Duration ~2h30m.",
                            Price = 1500m,
                            Route = "Islamabad to Peshawar",
                            TransportType = "Bus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
